adds a logrus hook to look context metadata.
skiprco/go-utils pull request #153
Opened 2022-05-20 12:42 UTC by gpomykala

tries to find context attached to logger and go-utils metadata in a context.
if found, will attach each metadata key to log entry.
same thing was done for audit logs, but it's better to have it on all logs.
things like operation_id shared on all service calls belonging to request will greatly help with troubleshooting in cloud environment.

Please note that this change only makes a difference if  logger call is preceded with attaching a context to a logger ie.
```
log.WithContext(ctx).Errorf(...)
```

2022-05-20 13:15 UTC, JensSkipr requested changes

2022-05-20 13:15 UTC, JensSkipr commented on logging/logger_context_metadata_hook.go
> +			entry.Data[snakeKey] = v
I think we should use a prefix when we inject such values into the logs to prevent any overwrites of the fields. E.g. `ctx_` in this case.

2022-05-20 13:15 UTC, JensSkipr commented on logging/logger_context_metadata_hook.go
> +		for k, v := range meta {
Before injecting the values, we should actually recalculate the `operation_time` (if we want to keep this feature). See `logging/audit_helpers.go` for the code:
```go
// Parse start to time
	start, err := time.Parse(time.RFC3339, startString)
	if err != nil {
		deriveLog.Error("Unable to parse operation_start_datetime as RFC3339")
		return "0"
	}

	// Time should not be initial
	if start.IsZero() {
		deriveLog.Error("operation_start_datetime should not contain a zero value")
		return "0"
	}

	// Derive and set operation_time
	operationTime := time.Since(start).Milliseconds()
	fields["operation_time"] = strconv.Itoa(operationTime)
```

2022-05-20 15:25 UTC, gpomykala commented on logging/logger_context_metadata_hook.go
> +		for k, v := range meta {
IMO timing the request is not a responsbility of logging.
that's responsbility of tracing ie. opentracing and metrics ie. prom metrics.
i propose to skip it here

2022-05-20 15:26 UTC, gpomykala commented on logging/logger_context_metadata_hook.go
> +			entry.Data[snakeKey] = v
ok

2022-05-23 06:13 UTC, JensSkipr commented on logging/logger_context_metadata_hook.go
> +		for k, v := range meta {
Non-blocking: We could use the timing for correct order in GCP logs (if they offer to sort on specific fields). But I agree on your message, so feel free to skip.

2022-05-23 06:58 UTC, JensSkipr approved these changes
Thanks!

2022-05-23 06:59 UTC, merged