BAN-99 feat(event): implement pubsub helpers
skiprco/go-utils pull request #275
Opened 2023-08-25 09:30 UTC by antoi-ne

# Description

| General info   |                     |
| -------------- | ------------------- |
| Linear ticket | BAN-99 |

TODO:
- [X] Implement watermill adapter for logrus #274 
- [x] Implement generic event repo for message serialisation + publication
- [x] Implement default configurations for watermill publishers & subscribers
- [x] Implement generic event handling router

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - mobile
  - web
  - partner
  - other
- This change requires a documentation update

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Unit tests
- Integration tests with Postgres
- Local tests with Postman
- Regression tests from quality-assurance repository

**Test Configuration**:

- Riva/business-api version:
- Wallet-api version :
- App version:
- Dashboard v2 version:

# Best Practices

- [ ] My code follows the [style guidelines of this project](https://github.com/skiprco/booking-api/blob/development/README.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding changes to the database and test fixtures
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any new or modified calls are reflected in postman collection
- [ ] I validated my development with the current frontend for retrocompatibilty (if needed)

# Security

**New Library (Packages, Dependencies) controls**

- [ ] No new library was introduced
- [ ] New library has been approved by the Security Officer (AS PR REVIEWER, with explicit comment)[^so_approval]
- [ ] New library has been added to the [list of used libraries](https://docs.google.com/spreadsheets/d/1UsJ3KG_2qWKiJWbShxy9l53uuJLIDj9-wpjtwk2bxXU/edit#gid=993688960)
- [ ] New library is available under acceptable license[^licenses]
- [ ] New library has available support (library is receiving updates)
- [ ] New library is monitored in case of vulnerability alert (e.g. via dependabot)
- [ ] New library is compliant, if relevant, with Skipr's GDPR Policy
- [ ] New library is compliant with Skipr's Security Policies (ISO 27001)

**Common controls**

- [ ] I verified that my code does not allow SQL injections
- [ ] I verified that my code does not reveal any sensitive data
- [ ] I included access rules
- [ ] I validated all inputs
- [ ] I sanitized all inputs
- [ ] The libraries I used are up to date and without any known vulnerabilities
- [ ] I have added sufficient logs with correct severity in order to facilitate debugging

# Documentation

- [Top 10 vulnerability for this PR](https://owasp.org/www-project-top-ten/)
- [OWASP](https://github.com/OWASP/Go-SCP/blob/master/dist/go-webapp-scp.pdf)

# Footnotes

[^so_approval]:
    In case of new library, Security Officer must confirm explicit validation,
    Validation is requested via PR, and should be confirm with explicit comment.

[^licenses]: Use of libraries through any of following licenses is not allowed:

    - GNU General Public License (GPL)
    - GNU Lesser General Public License (LGPL)
    - GNU Affero General Public License (AGPL)

This template is defined at https://github.com/skiprco/.github/blob/development/.github/pull_request_template.md

2023-09-20 15:16 UTC, aliphe requested changes

2023-09-20 15:16 UTC, aliphe commented on event/builder.go
> +	}
Please see comments on booking-api regarding functional builder/options pattern, this would translate here into 

```go
func NewBuilder(opts ...Option) *Builder {
	builder := &Builder{
		logger:   wla.New(logrus.StandardLogger()),
		handlers: make([]Handler, 0),
	}

	for _, opt := range opts {
		opt(builder)
	}

	return builder
}

func (b *Builder) WithLogrusLogger(logger *logrus.Logger) Option {
	return func(b *Builder) {
		b.logger = wla.New(logger)
	}
}
```
and so on. WDYT ?

2023-09-20 15:16 UTC, aliphe commented on event/builder.go
> +	gcpSub, err := googlecloud.NewSubscriber(googlecloud.SubscriberConfig{
This is exactly the kind of options that needs to be configurable, here you specify good defaults, but we might want to override these on a project basis, so having options like `WithRetryPolicy` or `WithProjectId` would be great :smile:

2023-09-20 15:16 UTC, aliphe commented on event/builder.go
> +func (b *Builder) BuildRouter() (*message.Router, error) {
For me we should be able to hide implementation details such as watermill dependency from our client applications, could we define Router, Publisher and Forwarder interfaces ? (and put each in their separate file in this package)
The whole `Builder...` naming feels odd as well, Builder is a pattern, I don't really want it to be the name of our struct. To me we should have one struct per main component (router, publisher, forwarder) and each should have their own functional builder and be independent, WDYT ?

2023-10-06 12:11 UTC, alienorlatour commented
From what I understand, there should be a paragraph in the repo's readme about each new library.

2023-10-06 12:31 UTC, alienorlatour reviewed
Write documentation in the comments for everything that is exported. This should not even lint.

2023-10-06 12:31 UTC, alienorlatour commented on event/publisher.go
> +	DefaultForwarderTopic = "forwarder_events"
This should have a comment or be unexported.

2023-10-06 12:31 UTC, alienorlatour commented on event/publisher.go
> +type Publisher interface {
Why do you need the interface to be exported and why is it declared here? Ideally, the publisher struct should be exported and the consumers should declare their own unexported micro interface.

2023-10-06 12:31 UTC, alienorlatour commented on event/router.go
> +	DefaultAckDeadline = time.Second * 300
Give a doc or avoid export. Or both.

2023-10-06 12:31 UTC, alienorlatour commented on event/router.go
> +	DefaultRetryPolicy = &pubsub.RetryPolicy{
An exported global variable is a source of problems. https://dave.cheney.net/2016/04/07/constant-errors

2023-10-06 12:31 UTC, alienorlatour commented on event/router.go
> +func WithRouterForwarderTopic(topic string) RouterOption {
Give documentation on these options. How are they used, how are they not used, what is the impact?

2023-10-19 09:53 UTC, aliphe reviewed
Looking great, just one nitpicking on package naming, because I feel like router has a bit too much of responsabilities and it's confusing

2023-10-19 09:53 UTC, aliphe commented on README.md
> +The Router has two tasks: picking up messages in the outbox to forward them to the intended PubSub topic and subscribe to specific pubsub topics to process their messages.
It feels like these two tasks should be handled by two separate packages for clarify.
I feel like the triade `Publisher` `Router` and `Subscriber` would be clear enough, WDYT ?

2023-10-19 10:05 UTC, antoi-ne commented on README.md
> +The Router has two tasks: picking up messages in the outbox to forward them to the intended PubSub topic and subscribe to specific pubsub topics to process their messages.
I agree, I can break the responsibility of the router into:
-  Router (or Subscriber, but I think I like the name Router more for this): handles subscribing to PubSub topics and processing events.
- Forwarder: listens for outbox messages and forwards them to the pubsub
so in the end we would en up with 3 types: Router, Forwarder, Publisher.
Did i understand correctly what you proposed?

2023-10-19 10:08 UTC, aliphe commented on README.md
> +The Router has two tasks: picking up messages in the outbox to forward them to the intended PubSub topic and subscribe to specific pubsub topics to process their messages.
Perfect 😄

2023-10-19 14:01 UTC, antoi-ne commented on README.md
> +The Router has two tasks: picking up messages in the outbox to forward them to the intended PubSub topic and subscribe to specific pubsub topics to process their messages.
done: 32a743e583c408628dc53ea7796c34de68e8368c

2023-10-20 14:55 UTC, aliphe approved these changes

2023-10-20 15:03 UTC, merged